runtime: python39

entrypoint: gunicorn -b:$PORT -w 4 main:app --worker-class gevent

handlers:
  - url: /static
    static_dir: static/
  - url: /uploads
    static_dir: uploads/
  - url: /.*
    script: app

#automatic_scaling:
#  min_instances: 1


env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "default"